### ISSUE TITLE
Ошибки при некорректной и регистрации авторизации

### ISSUE THREAD

**Issue by vsezbs** [Botik/help-children#42]
1. При некорректном логине/пароле при авторизации: "Пожалуйста, проверьте правильность написания логина и пароля."
Красным выделил место, в которое нужно поставить ошибку:
![image](https://user-images.githubusercontent.com/40119577/57615992-d10e8280-7585-11e9-805e-8186eb783b95.png)
2. При вводе данных существующего аккаунта (почты) при регистрации показывать ошибку "Такой email уже используется другим пользователем."
![image](https://user-images.githubusercontent.com/40119577/57616324-732e6a80-7586-11e9-96f2-91d89cfb97ed.png)

**Comment by vsezbs** [comment]
Так же необходимо убрать ограничение по длине почты
https://xn--c1accbmwfjbh2bd3o.xn--p1ai/registration
![image](https://user-images.githubusercontent.com/40119577/59509127-d62e5c80-8eb8-11e9-96dc-e2551ed154a9.png)

**Comment by Botik** [comment]
Это всё отдельные ишью.
Нельзя открывать уже решённые, смысл системы теряется.
Разные ошибки – разные ишью
https://github.com/Botik/help-children/commit/4a97662f85486989a47243915563668b67f29115
